gcc -ofod.exe fod.c probe/probe.c \
-DPROBE_IMPLEMENTED \
-Wall \
-Wno-unused-function \
-D__USE_MINGW_ANSI_STDIO=1 \
-DNNG_STATIC_LIB \
-I. \
-IC:/msys64/mingw64/include \
-I../shared/csc \
-LC:/msys64/mingw64/lib \
-Wl,-Bstatic \
-lnng \
-lws2_32 -lmswsock -ladvapi32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 \
-lopenblas \
-lm
